namespace E_POS.Application.Modules.Tenant.CatalogProduct.Dtos.TenantAdmin;

public sealed record SaveProductDraftCommand(
    Guid? ProductId,
    string ProductName,
    string ProductCode,
    string ProductSlug,
    string ProductStructure,
    Guid? CategoryId,
    Guid? BrandId,
    string? ShortDescription,
    string? LongDescription,
    string DesiredPublishStatus,
    bool PosSellable,
    bool TrackInventory,
    bool BatchTracking,
    bool ExpiryTracking,
    bool SerialTracking,
    bool AllowOnlineSale,
    int CurrentStage,
    int TargetSetupStep,
    long? ExpectedRowVersion,
    IReadOnlyList<Guid> StagedMediaAssetIds,
    string? UnitModel = null,
    Guid? BaseUnitId = null,
    Guid? SellingUnitId = null,
    Guid? PurchaseUnitId = null,
    Guid? OuterPackUnitId = null,
    decimal? ItemsPerPurchaseUnit = null,
    decimal? PurchaseUnitsPerOuterPack = null,
    bool AllowDecimalQuantity = false,
    bool IsExplicitDraftSave = false,
    string? WizardAction = null,
    VariantConfigurationDto? VariantConfiguration = null,
    BundleConfigurationDto? BundleConfiguration = null,
    string? BaseSku = null,
    string? ParentProductBarcode = null,
    IReadOnlyList<Step5VariantIdentifierDto>? VariantIdentifiers = null,
    IReadOnlyList<Step5AdditionalBarcodeDto>? AdditionalBarcodes = null);

