namespace E_POS.Application.Modules.Tenant.Reports.Dtos;

public sealed record ReportQueryDto(
    DateOnly? From,
    DateOnly? To,
    Guid? OutletId,
    Guid? TillId,
    Guid? CashierId,
    Guid? CustomerId,
    Guid? DepartmentId,
    Guid? CategoryId,
    Guid? SubcategoryId,
    Guid? BrandId,
    Guid? ProductId,
    Guid? ProductVariantId,
    Guid? SalesChannelId,
    Guid? PaymentMethodId,
    string? OrderStatus,
    string? PaymentStatus,
    string? StockStatus,
    string? ExpiryStatus,
    string? MovementType,
    string? BatchNumber,
    string? Search,
    string? Section,
    int Page = 1,
    int PageSize = 25,
    string? SortBy = null,
    string? SortDirection = "asc");
