using E_POS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace E_POS.Infrastructure.Persistence.Migrations;

[DbContext(typeof(EPosDbContext))]
[Migration("20260809220000_EnsureAuditLogsTableExists")]
public partial class EnsureAuditLogsTableExists : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS audit_logs (
                id bigint GENERATED BY DEFAULT AS IDENTITY,
                tenant_id uuid NULL,
                actor_user_id uuid NULL,
                actor_type varchar(30) NOT NULL,
                entity_type varchar(100) NOT NULL,
                entity_id uuid NULL,
                action varchar(100) NOT NULL,
                old_values jsonb NULL,
                new_values jsonb NULL,
                ip varchar(45) NULL,
                user_agent text NULL,
                created_at timestamp with time zone NOT NULL,
                CONSTRAINT pk_audit_logs PRIMARY KEY (id)
            );
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        // Intentionally non-destructive
    }
}
