using E_POS.Domain.Modules.AccessControl.Entities;
using E_POS.Domain.Modules.CatalogProduct.Entities;
using E_POS.Domain.Modules.Customer.Entities;
using E_POS.Domain.Modules.Inventory.Entities;
using E_POS.Domain.Modules.OutletTillDevice.Entities;
using E_POS.Domain.Modules.TenantFoundation.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace E_POS.Infrastructure.Modules.Inventory.Configurations;
public sealed class InventoryReservationConfiguration : IEntityTypeConfiguration<InventoryReservation>
{
    public void Configure(EntityTypeBuilder<InventoryReservation> builder)
    {
        builder.ToTable("inventory_reservations"); builder.HasKey(x => x.Id).HasName("pk_inventory_reservations"); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.CreatedAt).HasColumnName("created_at").HasColumnType("timestamp with time zone").IsRequired(); builder.Property(x => x.CreatedBy).HasColumnName("created_by_tenant_user_id").IsRequired(false); builder.Property(x => x.UpdatedAt).HasColumnName("updated_at").HasColumnType("timestamp with time zone").IsRequired(); builder.Property(x => x.UpdatedBy).HasColumnName("updated_by_tenant_user_id").IsRequired(false);
        builder.Property(x => x.TenantId).HasColumnName("tenant_id").IsRequired(); builder.Property(x => x.ReservationNumber).HasColumnName("reservation_number").HasColumnType("varchar(80)").HasMaxLength(80).IsRequired(); builder.Property(x => x.ReservationSource).HasColumnName("reservation_source").HasColumnType("varchar(40)").HasMaxLength(40).IsRequired(); builder.Property(x => x.SourceReferenceId).HasColumnName("source_reference_id").IsRequired(false); builder.Property(x => x.SourceReferenceNumber).HasColumnName("source_reference_number").HasColumnType("varchar(100)").HasMaxLength(100).IsRequired(false); builder.Property(x => x.SalesChannelId).HasColumnName("sales_channel_id").IsRequired(false); builder.Property(x => x.FulfillmentOutletId).HasColumnName("fulfillment_outlet_id").IsRequired(); builder.Property(x => x.CustomerId).HasColumnName("customer_id").IsRequired(false); builder.Property(x => x.ReservationStatus).HasColumnName("reservation_status").HasColumnType("varchar(40)").HasMaxLength(40).IsRequired(); builder.Property(x => x.ReservedAt).HasColumnName("reserved_at").HasColumnType("timestamp with time zone").IsRequired(); builder.Property(x => x.ExpiresAt).HasColumnName("expires_at").HasColumnType("timestamp with time zone").IsRequired(false); builder.Property(x => x.ReleasedAt).HasColumnName("released_at").HasColumnType("timestamp with time zone").IsRequired(false); builder.Property(x => x.ReleaseReason).HasColumnName("release_reason").HasColumnType("varchar(250)").HasMaxLength(250).IsRequired(false);
        builder.HasOne<Tenant>().WithMany().HasForeignKey(x => x.TenantId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_inventory_reservations_tenant_id_tenants"); builder.HasOne<SalesChannel>().WithMany().HasForeignKey(x => x.SalesChannelId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_inventory_reservations_sales_channel_id_sales_channels"); builder.HasOne<Outlet>().WithMany().HasForeignKey(x => x.FulfillmentOutletId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_inventory_reservations_fulfillment_outlet_id_outlets"); builder.HasOne<E_POS.Domain.Modules.Customer.Entities.Customer>().WithMany().HasForeignKey(x => x.CustomerId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_inventory_reservations_customer_id_customers");
        builder.HasIndex(x => new { x.TenantId, x.ReservationNumber }).IsUnique().HasDatabaseName("uq_inventory_reservations_tenant_id_reservation_number"); builder.ToTable(t => { t.HasCheckConstraint("ck_inventory_reservations_expires_at", "expires_at IS NULL OR expires_at >= reserved_at"); t.HasCheckConstraint("ck_inventory_reservations_released_at", "released_at IS NULL OR released_at >= reserved_at"); });
    }
}