using E_POS.Domain.Modules.AccessControl.Entities;
using E_POS.Domain.Modules.CatalogProduct.Entities;
using E_POS.Domain.Modules.Customer.Entities;
using E_POS.Domain.Modules.Inventory.Entities;
using E_POS.Domain.Modules.OutletTillDevice.Entities;
using E_POS.Domain.Modules.TenantFoundation.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace E_POS.Infrastructure.Modules.Inventory.Configurations;
public sealed class InventoryCostLayerConfiguration : IEntityTypeConfiguration<InventoryCostLayer>
{
    public void Configure(EntityTypeBuilder<InventoryCostLayer> builder)
    { builder.ToTable("inventory_cost_layers"); builder.HasKey(x => x.Id).HasName("pk_inventory_cost_layers"); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.CreatedAt).HasColumnName("created_at").HasColumnType("timestamp with time zone").IsRequired(); builder.Ignore(x => x.CreatedBy); builder.Property(x => x.UpdatedAt).HasColumnName("updated_at").HasColumnType("timestamp with time zone").IsRequired(); builder.Ignore(x => x.UpdatedBy); builder.Property(x => x.TenantId).HasColumnName("tenant_id").IsRequired(); builder.Property(x => x.InventoryBalanceId).HasColumnName("inventory_balance_id").IsRequired(); builder.Property(x => x.SourceStockMovementId).HasColumnName("source_stock_movement_id").IsRequired(); builder.Property(x => x.ReceivedQuantity).HasColumnName("received_quantity").HasPrecision(18, 4).IsRequired(); builder.Property(x => x.RemainingQuantity).HasColumnName("remaining_quantity").HasPrecision(18, 4).IsRequired(); builder.Property(x => x.UnitCost).HasColumnName("unit_cost").HasPrecision(18, 4).IsRequired(); builder.Property(x => x.TotalCost).HasColumnName("total_cost").HasPrecision(18, 4).IsRequired(); builder.Property(x => x.ReceivedAt).HasColumnName("received_at").HasColumnType("timestamp with time zone").IsRequired(); builder.Property(x => x.Status).HasColumnName("status").HasColumnType("varchar(30)").HasMaxLength(30).IsRequired(); builder.HasOne<Tenant>().WithMany().HasForeignKey(x => x.TenantId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_inventory_cost_layers_tenant_id_tenants"); builder.HasOne<InventoryBalance>().WithMany().HasForeignKey(x => x.InventoryBalanceId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_inventory_cost_layers_inventory_balance_id_inventory_balances"); builder.HasOne<StockMovement>().WithMany().HasForeignKey(x => x.SourceStockMovementId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_inventory_cost_layers_source_stock_movement_id_stock_movements"); builder.ToTable(t => { t.HasCheckConstraint("ck_inventory_cost_layers_received_quantity", "received_quantity > 0"); t.HasCheckConstraint("ck_inventory_cost_layers_remaining_quantity", "remaining_quantity >= 0 AND remaining_quantity <= received_quantity"); t.HasCheckConstraint("ck_inventory_cost_layers_costs", "unit_cost >= 0 AND total_cost >= 0"); }); }
}