using E_POS.Domain.Modules.AccessControl.Entities;
using E_POS.Domain.Modules.CatalogProduct.Entities;
using E_POS.Domain.Modules.Customer.Entities;
using E_POS.Domain.Modules.Inventory.Entities;
using E_POS.Domain.Modules.OutletTillDevice.Entities;
using E_POS.Domain.Modules.TenantFoundation.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace E_POS.Infrastructure.Modules.Inventory.Configurations;
public sealed class SerialNumberConfiguration : IEntityTypeConfiguration<SerialNumber>
{
    public void Configure(EntityTypeBuilder<SerialNumber> builder)
    { builder.ToTable("serial_numbers"); builder.HasKey(x => x.Id).HasName("pk_serial_numbers"); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.CreatedAt).HasColumnName("created_at").HasColumnType("timestamp with time zone").IsRequired(); builder.Property(x => x.CreatedBy).HasColumnName("created_by_tenant_user_id").IsRequired(false); builder.Property(x => x.UpdatedAt).HasColumnName("updated_at").HasColumnType("timestamp with time zone").IsRequired(); builder.Property(x => x.UpdatedBy).HasColumnName("updated_by_tenant_user_id").IsRequired(false); builder.Property(x => x.TenantId).HasColumnName("tenant_id").IsRequired(); builder.Property(x => x.ProductId).HasColumnName("product_id").IsRequired(); builder.Property(x => x.ProductVariantId).HasColumnName("product_variant_id").IsRequired(false); builder.Property(x => x.ProductBatchId).HasColumnName("product_batch_id").IsRequired(false); builder.Property(x => x.CurrentInventoryBalanceId).HasColumnName("current_inventory_balance_id").IsRequired(false); builder.Property(x => x.SerialNumberValue).HasColumnName("serial_number").HasColumnType("varchar(150)").HasMaxLength(150).IsRequired(); builder.Property(x => x.SerialStatus).HasColumnName("serial_status").HasColumnType("varchar(30)").HasMaxLength(30).IsRequired(); builder.Property(x => x.ReceivedAt).HasColumnName("received_at").HasColumnType("timestamp with time zone").IsRequired(false); builder.HasOne<Tenant>().WithMany().HasForeignKey(x => x.TenantId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_serial_numbers_tenant_id_tenants"); builder.HasOne<Product>().WithMany().HasForeignKey(x => x.ProductId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_serial_numbers_product_id_products"); builder.HasOne<ProductVariant>().WithMany().HasForeignKey(x => x.ProductVariantId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_serial_numbers_product_variant_id_product_variants"); builder.HasOne<ProductBatch>().WithMany().HasForeignKey(x => x.ProductBatchId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_serial_numbers_product_batch_id_product_batches"); builder.HasOne<InventoryBalance>().WithMany().HasForeignKey(x => x.CurrentInventoryBalanceId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_serial_numbers_current_inventory_balance_id_inventory_balances"); builder.HasIndex(x => new { x.TenantId, x.ProductId, x.SerialNumberValue }).IsUnique().HasDatabaseName("uq_serial_numbers_tenant_id_product_id_serial_number"); builder.HasIndex(x => new { x.TenantId, x.Id }).IsUnique().HasDatabaseName("uq_serial_numbers_tenant_id_id"); }
}