using E_POS.Domain.Modules.AccessControl.Entities;
using E_POS.Domain.Modules.CatalogProduct.Entities;
using E_POS.Domain.Modules.Inventory.Entities;
using E_POS.Domain.Modules.TenantFoundation.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace E_POS.Infrastructure.Modules.Inventory.Configurations;
public sealed class StockAdjustmentLineConfiguration : IEntityTypeConfiguration<StockAdjustmentLine>
{
    public void Configure(EntityTypeBuilder<StockAdjustmentLine> builder)
    { builder.ToTable("stock_adjustment_lines"); builder.HasKey(x => x.Id).HasName("pk_stock_adjustment_lines"); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.CreatedAt).HasColumnName("created_at").HasColumnType("timestamp with time zone").IsRequired(); builder.Ignore(x => x.CreatedBy); builder.Property(x => x.UpdatedAt).HasColumnName("updated_at").HasColumnType("timestamp with time zone").IsRequired(); builder.Ignore(x => x.UpdatedBy); builder.Property(x => x.TenantId).HasColumnName("tenant_id").IsRequired(); builder.Property(x => x.StockAdjustmentId).HasColumnName("stock_adjustment_id").IsRequired(); builder.Property(x => x.LineNumber).HasColumnName("line_number").IsRequired(); builder.Property(x => x.ProductId).HasColumnName("product_id").IsRequired(); builder.Property(x => x.ProductVariantId).HasColumnName("product_variant_id").IsRequired(false); builder.Property(x => x.ProductBatchId).HasColumnName("product_batch_id").IsRequired(false); builder.Property(x => x.QuantityBefore).HasColumnName("quantity_before").HasPrecision(18, 4).IsRequired(); builder.Property(x => x.QuantityChange).HasColumnName("quantity_change").HasPrecision(18, 4).IsRequired(); builder.Property(x => x.QuantityAfter).HasColumnName("quantity_after").HasPrecision(18, 4).IsRequired(); builder.Property(x => x.UnitCost).HasColumnName("unit_cost").HasPrecision(18, 4).IsRequired(false); builder.Property(x => x.LineNote).HasColumnName("line_note").HasColumnType("text").IsRequired(false); builder.HasOne<Tenant>().WithMany().HasForeignKey(x => x.TenantId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_stock_adjustment_lines_tenant_id_tenants"); builder.HasOne<StockAdjustment>().WithMany().HasForeignKey(x => x.StockAdjustmentId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_stock_adjustment_lines_stock_adjustment_id_stock_adjustments"); builder.HasOne<Product>().WithMany().HasForeignKey(x => x.ProductId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_stock_adjustment_lines_product_id_products"); builder.HasOne<ProductVariant>().WithMany().HasForeignKey(x => x.ProductVariantId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_stock_adjustment_lines_product_variant_id_product_variants"); builder.HasOne<ProductBatch>().WithMany().HasForeignKey(x => x.ProductBatchId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_stock_adjustment_lines_product_batch_id_product_batches"); builder.HasIndex(x => new { x.TenantId, x.StockAdjustmentId, x.LineNumber }).IsUnique().HasDatabaseName("uq_stock_adjustment_lines_tenant_id_stock_adjustment_id_line_number"); builder.HasIndex(x => new { x.TenantId, x.StockAdjustmentId, x.ProductId, x.ProductVariantId, x.ProductBatchId }).IsUnique().HasDatabaseName("uq_stock_adjustment_lines_scope").AreNullsDistinct(false); }
}