using E_POS.Domain.Modules.AccessControl.Entities;
using E_POS.Domain.Modules.CatalogProduct.Entities;
using E_POS.Domain.Modules.Inventory.Entities;
using E_POS.Domain.Modules.TenantFoundation.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace E_POS.Infrastructure.Modules.Inventory.Configurations;
public sealed class StockMovementCostAllocationConfiguration : IEntityTypeConfiguration<StockMovementCostAllocation>
{
    public void Configure(EntityTypeBuilder<StockMovementCostAllocation> builder)
    { builder.ToTable("stock_movement_cost_allocations"); builder.HasKey(x => x.Id).HasName("pk_stock_movement_cost_allocations"); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.CreatedAt).HasColumnName("created_at").HasColumnType("timestamp with time zone").IsRequired(); builder.Ignore(x => x.CreatedBy); builder.Ignore(x => x.UpdatedAt); builder.Ignore(x => x.UpdatedBy); builder.Property(x => x.TenantId).HasColumnName("tenant_id").IsRequired(); builder.Property(x => x.StockMovementId).HasColumnName("stock_movement_id").IsRequired(); builder.Property(x => x.InventoryCostLayerId).HasColumnName("inventory_cost_layer_id").IsRequired(); builder.Property(x => x.AllocatedQuantity).HasColumnName("allocated_quantity").HasPrecision(18, 4).IsRequired(); builder.Property(x => x.UnitCost).HasColumnName("unit_cost").HasPrecision(18, 4).IsRequired(); builder.Property(x => x.TotalCost).HasColumnName("total_cost").HasPrecision(18, 4).IsRequired(); builder.HasOne<Tenant>().WithMany().HasForeignKey(x => x.TenantId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_stock_movement_cost_allocations_tenant_id_tenants"); builder.HasOne<StockMovement>().WithMany().HasForeignKey(x => x.StockMovementId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_stock_movement_cost_allocations_stock_movement_id_stock_movements"); builder.HasOne<InventoryCostLayer>().WithMany().HasForeignKey(x => x.InventoryCostLayerId).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_stock_movement_cost_allocations_inventory_cost_layer_id_inventory_cost_layers"); builder.HasIndex(x => new { x.TenantId, x.StockMovementId, x.InventoryCostLayerId }).IsUnique().HasDatabaseName("uq_stock_movement_cost_allocations_tenant_id_stock_movement_id_inventory_cost_layer_id"); builder.ToTable(t => { t.HasCheckConstraint("ck_stock_movement_cost_allocations_allocated_quantity", "allocated_quantity > 0"); t.HasCheckConstraint("ck_stock_movement_cost_allocations_costs", "unit_cost >= 0 AND total_cost >= 0"); }); }
}